# Taller Integrador: Consumo de APIs + Power BI

## Objetivo

El presente proyecto tiene como propósito realizar un proceso completo de extracción, transformación y visualización de datos utilizando una API pública, Python y Power BI. Para ello se empleará la API de Studio Ghibli, la cual contiene información sobre películas. Posteriormente los datos serán limpiados, transformados y exportados a un archivo CSV para construir un dashboard interactivo en Power BI.

In [15]:
!pip install requests pandas matplotlib

Requirement already satisfied: requests in c:\users\liz00\appdata\local\programs\python\python311\lib\site-packages (2.34.1)
Requirement already satisfied: pandas in c:\users\liz00\appdata\local\programs\python\python311\lib\site-packages (3.0.1)
Requirement already satisfied: matplotlib in c:\users\liz00\appdata\local\programs\python\python311\lib\site-packages (3.10.9)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\liz00\appdata\local\programs\python\python311\lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\liz00\appdata\local\programs\python\python311\lib\site-packages (from requests) (3.15)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\liz00\appdata\local\programs\python\python311\lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\liz00\appdata\local\programs\python\python311\lib\site-packages (from requests) (2026.4.22)
Requirement already satisfied: numpy>=1.26.0 in c:\users\liz00\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\liz00\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\liz00\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\liz00\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\liz00\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\liz00\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\liz00\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\liz00\appdata\roaming\python\python311\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\liz00\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\liz00\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\users\liz00\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# Importación de librerías

En esta sección se importan las librerías necesarias para el desarrollo del proyecto.

La librería requests permitirá realizar consultas a la API pública mediante peticiones HTTP.

La librería pandas permitirá transformar y manipular los datos obtenidos en estructuras tabulares tipo DataFrame, facilitando su limpieza y análisis posterior.

In [16]:
import requests
import pandas as pd

# Definición de la API y consulta de datos mediante petición HTTP

Se define la dirección URL de la API pública que será utilizada para obtener la información.

La API seleccionada corresponde a Studio Ghibli (https://ghibliapi.vercel.app/films) y contiene datos relacionados con películas como nombre, director, duración y calificación.

Explicación:

- requests.get() hace la consulta
- json() convierte la respuesta a diccionario Python
- datos[:2] Antes de realizar transformaciones es importante inspeccionar la estructura inicial de la información obtenida. Se visualizarán los primeros registros para verificar que la consulta se realizó correctamente.

In [17]:
url="https://ghibliapi.vercel.app/films"

respuesta=requests.get(url)

datos=respuesta.json()

datos[:2]

[{'id': '2baf70d1-42bb-4437-b551-e5fed5a87abe',
  'title': 'Castle in the Sky',
  'original_title': '天空の城ラピュタ',
  'original_title_romanised': 'Tenkū no shiro Rapyuta',
  'image': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/npOnzAbLh6VOIu3naU5QaEcTepo.jpg',
  'movie_banner': 'https://image.tmdb.org/t/p/w533_and_h300_bestv2/3cyjYtLWCBE1uvWINHFsFnE8LUK.jpg',
  'description': "The orphan Sheeta inherited a mysterious crystal that links her to the mythical sky-kingdom of Laputa. With the help of resourceful Pazu and a rollicking band of sky pirates, she makes her way to the ruins of the once-great civilization. Sheeta and Pazu must outwit the evil Muska, who plans to use Laputa's science to make himself ruler of the world.",
  'director': 'Hayao Miyazaki',
  'producer': 'Isao Takahata',
  'release_date': '1986',
  'running_time': '124',
  'rt_score': '95',
  'people': ['https://ghibliapi.vercel.app/people/598f7048-74ff-41e0-92ef-87dc1ad980a9',
   'https://ghibliapi.vercel.app/people/fe93adf2-2f3a-4ec4-9f68-5422f1b87c01',
   'https://ghibliapi.vercel.app/people/3bc0b41e-3569-4d20-ae73-2da329bf0786',
   'https://ghibliapi.vercel.app/people/40c005ce-3725-4f15-8409-3e1b1b14b583',
   'https://ghibliapi.vercel.app/people/5c83c12a-62d5-4e92-8672-33ac76ae1fa0',
   'https://ghibliapi.vercel.app/people/e08880d0-6938-44f3-b179-81947e7873fc',
   'https://ghibliapi.vercel.app/people/2a1dad70-802a-459d-8cc2-4ebd8821248b'],
  'species': ['https://ghibliapi.vercel.app/species/af3910a6-429f-4c74-9ad5-dfe1c4aa04f2'],
  'locations': ['https://ghibliapi.vercel.app/locations/'],
  'vehicles': ['https://ghibliapi.vercel.app/vehicles/4e09b023-f650-4747-9ab9-eacf14540cfb'],
  'url': 'https://ghibliapi.vercel.app/films/2baf70d1-42bb-4437-b551-e5fed5a87abe'},
 {'id': '12cfb892-aac0-4c5b-94af-521852e46d6a',
  'title': 'Grave of the Fireflies',
  'original_title': '火垂るの墓',
  'original_title_romanised': 'Hotaru no haka',
  'image': 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/qG3RYlIVpTYclR9TYIsy8p7m7AT.jpg',
  'movie_banner': 'https://image.tmdb.org/t/p/original/vkZSd0Lp8iCVBGpFH9L7LzLusjS.jpg',
  'description': 'In the latter part of World War II, a boy and his sister, orphaned when their mother is killed in the firebombing of Tokyo, are left to survive on their own in what remains of civilian life in Japan. The plot follows this boy and his sister as they do their best to survive in the Japanese countryside, battling hunger, prejudice, and pride in their own quiet, personal battle.',
  'director': 'Isao Takahata',
  'producer': 'Toru Hara',
  'release_date': '1988',
  'running_time': '89',
  'rt_score': '97',
  'people': ['https://ghibliapi.vercel.app/people/'],
  'species': ['https://ghibliapi.vercel.app/species/af3910a6-429f-4c74-9ad5-dfe1c4aa04f2'],
  'locations': ['https://ghibliapi.vercel.app/locations/'],
  'vehicles': ['https://ghibliapi.vercel.app/vehicles/'],
  'url': 'https://ghibliapi.vercel.app/films/12cfb892-aac0-4c5b-94af-521852e46d6a'}]

# Conversión de JSON a DataFrame

La información proveniente de la API se encuentra en formato JSON.

Para facilitar el análisis y procesamiento de los datos, estos serán convertidos a un DataFrame utilizando la librería pandas.

In [18]:
df=pd.DataFrame(datos)

# Visualización inicial del DataFrame

Se muestran las primeras filas del conjunto de datos para identificar la estructura y contenido de las variables disponibles.

In [19]:
df.head()

,id,title,original_title,original_title_romanised,image,movie_banner,description,director,producer,release_date,running_time,rt_score,people,species,locations,vehicles,url
0,2baf70d1-42bb-4437-b551-e5fed5a87abe,Castle in the Sky,天空の城ラピュタ,Tenkū no shiro Rapyuta,https://image.tmdb.org/t/p/w600_and_h900_bestv...,https://image.tmdb.org/t/p/w533_and_h300_bestv...,The orphan Sheeta inherited a mysterious cryst...,Hayao Miyazaki,Isao Takahata,1986,124,95,[https://ghibliapi.vercel.app/people/598f7048-...,[https://ghibliapi.vercel.app/species/af3910a6...,[https://ghibliapi.vercel.app/locations/],[https://ghibliapi.vercel.app/vehicles/4e09b02...,https://ghibliapi.vercel.app/films/2baf70d1-42...
1,12cfb892-aac0-4c5b-94af-521852e46d6a,Grave of the Fireflies,火垂るの墓,Hotaru no haka,https://image.tmdb.org/t/p/w600_and_h900_bestv...,https://image.tmdb.org/t/p/original/vkZSd0Lp8i...,"In the latter part of World War II, a boy and ...",Isao Takahata,Toru Hara,1988,89,97,[https://ghibliapi.vercel.app/people/],[https://ghibliapi.vercel.app/species/af3910a6...,[https://ghibliapi.vercel.app/locations/],[https://ghibliapi.vercel.app/vehicles/],https://ghibliapi.vercel.app/films/12cfb892-aa...
2,58611129-2dbc-4a81-a72f-77ddfc1b1b49,My Neighbor Totoro,となりのトトロ,Tonari no Totoro,https://image.tmdb.org/t/p/w600_and_h900_bestv...,https://image.tmdb.org/t/p/original/etqr6fOOCX...,Two sisters move to the country with their fat...,Hayao Miyazaki,Hayao Miyazaki,1988,86,93,[https://ghibliapi.vercel.app/people/986faac6-...,[https://ghibliapi.vercel.app/species/af3910a6...,[https://ghibliapi.vercel.app/locations/],[https://ghibliapi.vercel.app/vehicles/],https://ghibliapi.vercel.app/films/58611129-2d...
3,ea660b10-85c4-4ae3-8a5f-41cea3648e3e,Kiki's Delivery Service,魔女の宅急便,Majo no takkyūbin,https://image.tmdb.org/t/p/w600_and_h900_bestv...,https://image.tmdb.org/t/p/original/h5pAEVma83...,"A young witch, on her mandatory year of indepe...",Hayao Miyazaki,Hayao Miyazaki,1989,102,96,[https://ghibliapi.vercel.app/people/2409052a-...,[https://ghibliapi.vercel.app/species/af3910a6...,[https://ghibliapi.vercel.app/locations/],[https://ghibliapi.vercel.app/vehicles/],https://ghibliapi.vercel.app/films/ea660b10-85...
4,4e236f34-b981-41c3-8c65-f8c9000b94e7,Only Yesterday,おもひでぽろぽろ,Omoide poro poro,https://image.tmdb.org/t/p/w600_and_h900_bestv...,https://image.tmdb.org/t/p/w533_and_h300_bestv...,"It’s 1982, and Taeko is 27 years old, unmarrie...",Isao Takahata,Toshio Suzuki,1991,118,100,[https://ghibliapi.vercel.app/people/],[https://ghibliapi.vercel.app/species/af3910a6...,[https://ghibliapi.vercel.app/locations/],[https://ghibliapi.vercel.app/vehicles/],https://ghibliapi.vercel.app/films/4e236f34-b9...

# Exploración de variables disponibles

En esta etapa se identifican las columnas existentes dentro del conjunto de datos para seleccionar únicamente aquellas que serán útiles para el análisis y visualización.

In [20]:
df.columns

Index(['id', 'title', 'original_title', 'original_title_romanised', 'image',
       'movie_banner', 'description', 'director', 'producer', 'release_date',
       'running_time', 'rt_score', 'people', 'species', 'locations',
       'vehicles', 'url'],
      dtype='str')

# Selección de variables relevantes

Se seleccionan únicamente las variables que aportarán valor al análisis:

- Título
- Director
- Productor
- Año
- Duración
- Calificación

Esto permite trabajar con un conjunto de datos más limpio y enfocado.

In [21]:
df=df[
[
'title',
'director',
'producer',
'release_date',
'running_time',
'rt_score'
]
]

# Visualización de la nueva estructura

Después de filtrar las variables necesarias se revisan nuevamente los datos para confirmar los cambios realizados.

In [22]:
df.head()

,title,director,producer,release_date,running_time,rt_score
0,Castle in the Sky,Hayao Miyazaki,Isao Takahata,1986,124,95
1,Grave of the Fireflies,Isao Takahata,Toru Hara,1988,89,97
2,My Neighbor Totoro,Hayao Miyazaki,Hayao Miyazaki,1988,86,93
3,Kiki's Delivery Service,Hayao Miyazaki,Hayao Miyazaki,1989,102,96
4,Only Yesterday,Isao Takahata,Toshio Suzuki,1991,118,100

# Transformación de tipos de datos

Algunas variables numéricas se encuentran almacenadas como texto.

Para poder realizar cálculos y visualizaciones correctamente es necesario convertirlas a formato numérico.

In [23]:
df['release_date']=pd.to_numeric(df['release_date'])

df['running_time']=pd.to_numeric(df['running_time'])

df['rt_score']=pd.to_numeric(df['rt_score'])

# Renombramiento de columnas

Se modifican los nombres originales de las variables por nombres más descriptivos y fáciles de interpretar dentro de Power BI.

In [24]:
df.columns=[
'Titulo',
'Director',
'Productor',
'Año',
'Duracion_Min',
'Calificacion'
]
df.head()

,Titulo,Director,Productor,Año,Duracion_Min,Calificacion
0,Castle in the Sky,Hayao Miyazaki,Isao Takahata,1986,124,95
1,Grave of the Fireflies,Isao Takahata,Toru Hara,1988,89,97
2,My Neighbor Totoro,Hayao Miyazaki,Hayao Miyazaki,1988,86,93
3,Kiki's Delivery Service,Hayao Miyazaki,Hayao Miyazaki,1989,102,96
4,Only Yesterday,Isao Takahata,Toshio Suzuki,1991,118,100

# Creación de una nueva variable categórica

Se creará una nueva variable denominada Tipo_Duración.

Esta variable clasificará las películas según su duración:

- Corta
- Media
- Larga

Esto facilitará posteriores análisis y filtros en Power BI.

In [25]:
def categoria_duracion(x):

    if x<90:
        return "Corta"

    elif x<120:
        return "Media"

    else:
        return "Larga"

df["Tipo_Duracion"]=df["Duracion_Min"].apply(categoria_duracion)

# Visualización del conjunto de datos transformado

Se revisan nuevamente los datos para comprobar la correcta creación de la nueva variable y validar la estructura final.

In [26]:
df.head()

,Titulo,Director,Productor,Año,Duracion_Min,Calificacion,Tipo_Duracion
0,Castle in the Sky,Hayao Miyazaki,Isao Takahata,1986,124,95,Larga
1,Grave of the Fireflies,Isao Takahata,Toru Hara,1988,89,97,Corta
2,My Neighbor Totoro,Hayao Miyazaki,Hayao Miyazaki,1988,86,93,Corta
3,Kiki's Delivery Service,Hayao Miyazaki,Hayao Miyazaki,1989,102,96,Media
4,Only Yesterday,Isao Takahata,Toshio Suzuki,1991,118,100,Media

# Verificación de valores faltantes

Es importante verificar si existen datos nulos o vacíos dentro del conjunto de datos.

La presencia de valores faltantes podría afectar los análisis y visualizaciones posteriores.

In [27]:
df.isnull().sum()

Titulo           0
Director         0
Productor        0
Año              0
Duracion_Min     0
Calificacion     0
Tipo_Duracion    0
dtype: int64

# Exportación del conjunto de datos

Finalmente se exportará el conjunto de datos procesado y limpio a un archivo CSV.

Este archivo será utilizado posteriormente en Power BI para la construcción del dashboard interactivo.

In [28]:
df.to_csv(
"peliculas_ghibli.csv",
index=False
)

print("Archivo CSV creado correctamente")

Archivo CSV creado correctamente

# Conclusión

Se realizó satisfactoriamente el proceso de extracción, transformación y preparación de datos a partir de una API pública utilizando Python.

Los datos obtenidos fueron limpiados, estructurados y exportados a un archivo CSV listo para ser utilizado en Power BI, permitiendo continuar con la etapa de visualización y generación de conocimiento.